
name: 'pragmatic_data_integration_tests'
version: '0.1.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

# These configurations specify where dbt should look for different types of files.
analysis-paths: ["analyses"]
macro-paths: ["macros", "in_out"]
model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
models:
  pragmatic_data_integration_tests:
    +schema: MODELS
    +materialized: table

seeds:
  pragmatic_data_integration_tests:
    inputs:
      +schema: INPUTS
    expected:
      +schema: EXPECTED

# Variables
vars:
  'dbt_date:time_zone': 'America/Los_Angeles'


# COPYRIGHT & LICENSE
# (C) Copyright 2022-2024 Roberto Zagni.
# All right reserved.

# This software is licensed with a dual license based on the use of the software.
# Licensed under the PROPRIETARY LICENSE for use in consulting, billable work or any other work performed in association with a commercial transaction or when it is not explicitly granted another licence.
# Licensed under the APACHE LICENSE only for use in personal, non commercial, academic or internal use in own systems by Legal Entities for work performed by employees of such Legal Entities. This explicitly excludes any consulting or work for hire use.
# Unless agreed to in writing, software distributed under the Licenses is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the Licenses for the specific language governing permissions and limitations under the Licenses.
# If you are unable to accept the above terms you may not use this file and any content of this repository.
